/* 数据定义 */


const DECK_SHIPIN = [
  {front:"群臣吏民能面刺寡人之过者",hl:"面",word:"面",meaning:"当面",analogy:"像「当面」说一样，face to face"},
  {front:"邹忌修八尺有余",hl:"修",word:"修",meaning:"身高",analogy:"相当于「身高/长度」"},
  {front:"徐公何能及君也",hl:"及",word:"及",meaning:"比得上",analogy:"= 赶得上/比得上"},
  {front:"吾妻之美我者，私我也",hl:"私",word:"私",meaning:"偏私/偏爱",analogy:"= 私下偏向"},
  {front:"能谤讥于市朝",hl:"谤讥",word:"谤讥",meaning:"公开批评议论",analogy:"≈ 公开提意见（非贬义）"},
  {front:"闻寡人之耳者",hl:"闻",word:"闻",meaning:"使……听到",analogy:"= 让……听见"},
  {front:"于是入朝见威王",hl:"朝",word:"朝",meaning:"朝廷",analogy:"= 上朝/朝廷"},
  {front:"数月之后，时时而间进",hl:"间",word:"间",meaning:"间或/偶尔",analogy:"= occasionally"},
  {front:"此所谓战胜于朝廷",hl:"战胜",word:"战胜",meaning:"取胜",analogy:"在朝廷上取胜（无需出兵）"},
  {front:"先帝创业未半而中道崩殂",hl:"崩殂",word:"崩殂",meaning:"帝王去世",analogy:"= 驾崩"},
  {front:"此诚危急存亡之秋也",hl:"秋",word:"秋",meaning:"时候/时期",analogy:"= 关键时刻"},
  {front:"盖追先帝之殊遇",hl:"殊遇",word:"殊遇",meaning:"特殊的厚待",analogy:"=特别待遇"},
  {front:"是以先帝简拔以遗陛下",hl:"简拔",word:"简拔",meaning:"选拔",analogy:"= 挑选提拔"},
  {front:"性行淑均",hl:"淑均",word:"淑均",meaning:"善良公正",analogy:"= 品性善良公正"},
  {front:"未尝不叹息痛恨于桓灵也",hl:"痛恨",word:"痛恨",meaning:"痛心遗憾",analogy:"古义≠今义；不是恨，是遗憾"},
  {front:"由是感激，遂许先帝以驱驰",hl:"感激",word:"感激",meaning:"感动奋发",analogy:"= 感动+激奋"},
  {front:"深入不毛",hl:"不毛",word:"不毛",meaning:"不长草木之地",analogy:"= 不长草木的地方"},
  {front:"攘除奸凶",hl:"攘除",word:"攘除",meaning:"排除/铲除",analogy:"= 铲除"},
  {front:"临表涕零",hl:"涕",word:"涕",meaning:"眼泪",analogy:"≠鼻涕；古义为眼泪"},
  {front:"以光先帝遗德",hl:"光",word:"光",meaning:"发扬光大",analogy:"= 使……光大"},
  {front:"道中手自抄录",hl:"手",word:"手",meaning:"亲手（名词作状语）",analogy:"= by hand/亲手"},
  {front:"与之论辩，言和而色夷",hl:"夷",word:"夷",meaning:"平和",analogy:"= 平易/平和"},
  {front:"余幼时即嗜学",hl:"嗜",word:"嗜",meaning:"特别爱好",analogy:"= 沉迷于/酷爱"},
  {front:"家贫，无从致书以观",hl:"致",word:"致",meaning:"得到",analogy:"= 弄到/获得"},
  {front:"益慕圣贤之道",hl:"慕",word:"慕",meaning:"仰慕",analogy:"= 仰慕/敬佩"},
  {front:"尝趋百里外",hl:"趋",word:"趋",meaning:"快步走",analogy:"= 快走/奔赴"},
  {front:"从乡之先达执经叩问",hl:"叩问",word:"叩问",meaning:"请教",analogy:"= 敲门请教"},
  {front:"门人弟子填其室",hl:"填",word:"填",meaning:"挤满",analogy:"= 塞满/人多"},
  {front:"援疑质理",hl:"质",word:"质",meaning:"询问",analogy:"= 质问/询问"},
  {front:"俯身倾耳以请",hl:"倾",word:"倾",meaning:"侧着",analogy:"= 倾侧/侧耳倾听"},
  {front:"俟其欣悦，则又请焉",hl:"俟",word:"俟",meaning:"等待",analogy:"= wait/等候"},
  {front:"卒获有所闻",hl:"卒",word:"卒",meaning:"终于",analogy:"= finally/最终"},
  {front:"故余虽愚，卒获有所闻",hl:"虽",word:"虽",meaning:"即使",analogy:"= even if"},
  {front:"穷冬烈风，大雪深数尺",hl:"穷冬",word:"穷冬",meaning:"深冬/严冬",analogy:"= 极冷的冬天"},
  {front:"足肤皲裂而不知",hl:"皲裂",word:"皲裂",meaning:"皮肤冻裂",analogy:"= 皮肤开裂"},
  {front:"媵人持汤沃灌",hl:"汤",word:"汤",meaning:"热水",analogy:"≠菜汤；古义为热水"},
  {front:"以衾拥覆，久而乃和",hl:"和",word:"和",meaning:"暖和",analogy:"= 暖和/warm"},
  {front:"寓逆旅，主人日再食",hl:"再",word:"再",meaning:"两次",analogy:"= 两次（不是again）"},
  {front:"右备容臭",hl:"容臭",word:"容臭",meaning:"香囊/气味",analogy:"≠臭味；古义为香气"},
  {front:"烨然若神人",hl:"烨然",word:"烨然",meaning:"光彩照人的样子",analogy:"= 光彩耀眼"},
  {front:"余则缊袍敝衣处其间",hl:"缊",word:"缊",meaning:"破旧/乱麻",analogy:"= 破旧的"},
  {front:"略无慕艳意",hl:"慕艳",word:"慕艳",meaning:"羡慕",analogy:"= 羡慕"},
  {front:"以中有足乐者",hl:"以",word:"以",meaning:"因为",analogy:"= because"},
  {front:"不知口体之奉不若人也",hl:"奉",word:"奉",meaning:"供养/享受",analogy:"= 待遇/供给"},
  {front:"盖余之勤且艰若此",hl:"盖",word:"盖",meaning:"大概/发语词",analogy:"≈ 大概是这样"},
  {front:"今虽耄老，未有所成",hl:"耄老",word:"耄老",meaning:"年老（八九十岁）",analogy:"= 老年"},
  {front:"犹幸预君子之列",hl:"预",word:"预",meaning:"参与",analogy:"= 参与/列入"},
  {front:"而承天子之宠光",hl:"宠光",word:"宠光",meaning:"恩宠荣耀",analogy:"= 恩宠和荣耀"},
  {front:"缀公卿之后",hl:"缀",word:"缀",meaning:"跟随/列于",analogy:"= 跟在……后面"},
  {front:"非天质之卑，则心不若余之专耳",hl:"卑",word:"卑",meaning:"低下",analogy:"= 资质差 vs 专心不够"},
  {front:"辍耕之垄上",hl:"之",word:"之",meaning:"去/往（动词）",analogy:"= go to"},
  {front:"苟富贵，无相忘",hl:"苟",word:"苟",meaning:"如果",analogy:"= if"},
  {front:"燕雀安知鸿鹄之志哉",hl:"安",word:"安",meaning:"怎么",analogy:"= how could"},
  {front:"会天大雨，道不通",hl:"会",word:"会",meaning:"恰逢",analogy:"= 碰巧遇到"},
  {front:"度已失期",hl:"度",word:"度",meaning:"估计（duó）",analogy:"= 推测/估量"},
  {front:"今亡亦死，举大计亦死",hl:"亡",word:"亡",meaning:"逃跑",analogy:"≠死亡；此处指逃亡"},
  {front:"等死，死国可乎",hl:"等",word:"等",meaning:"同样",analogy:"= equally"},
  {front:"天下苦秦久矣",hl:"苦",word:"苦",meaning:"被……所苦",analogy:"= 受……之苦"},
];




const DECK_WENXUE = [
  {front:"《诗经》开创什么体裁？",hl:"",word:"风雅颂",meaning:"风(民歌)雅(宫廷)颂(祭祀)",analogy:"风在民间吹，雅在殿堂吟，颂在祭坛唱"},
  {front:"《离骚》谁的代表作？",hl:"",word:"屈原",meaning:"浪漫主义源头+香草美人手法",analogy:"香草美人=借花喻人"},
  {front:"《史记》作者与体例？",hl:"",word:"司马迁·纪传体通史",meaning:"究天人之际，通古今之变",analogy:"第一部纪传体通史"},
  {front:"唐宋八大家？",hl:"",word:"韩柳+三苏+欧曾王",meaning:"韩愈柳宗元+三苏+欧阳修曾巩王安石",analogy:"韩柳三苏欧曾王，古文运动扛大梁"},
  {front:"唐诗分哪四期？",hl:"",word:"初唐/盛唐/中唐/晚唐",meaning:"初唐四杰→李杜→白居易→小李杜",analogy:"王杨卢骆开新篇，李杜光芒照盛唐"},
  {front:"宋词两大流派？",hl:"",word:"婉约 vs 豪放",meaning:"婉约(柳永李清照)豪放(苏轼辛弃疾)",analogy:"婉约儿女情长，豪放家国天下"},
  {front:"元曲四大家？",hl:"",word:"关马郑白",meaning:"关汉卿马致远郑光祖白朴",analogy:""},
  {front:"四大名著？",hl:"",word:"红·清/三·明/水·明/西·明",meaning:"红楼梦三国水浒西游",analogy:"明清小说四座山"},
  {front:"鲁迅代表作？",hl:"",word:"《呐喊》《彷徨》《朝花夕拾》",meaning:"中国现代文学奠基人",analogy:"横眉冷对千夫指，俯首甘为孺子牛"},
  {front:"《论语》体裁？",hl:"",word:"语录体·孔子弟子及再传弟子",meaning:"半部论语可治天下",analogy:""},
  {front:"《孟子》核心思想？",hl:"",word:"民贵君轻·性善论",meaning:"论辩体，孟子与弟子合著",analogy:""},
  {front:"陶渊明地位？",hl:"",word:"田园诗派鼻祖",meaning:"采菊东篱下，悠然见南山",analogy:""},
  {front:"杜甫称号？",hl:"",word:"诗圣·诗史",meaning:"沉郁顿挫，忧国忧民",analogy:""},
  {front:"李白称号？",hl:"",word:"诗仙·浪漫主义",meaning:"笔落惊风雨，诗成泣鬼神",analogy:""},
  {front:"苏轼成就？",hl:"",word:"豪放派代表+全才",meaning:"诗文书画全能",analogy:"一蓑烟雨任平生"},
  {front:"曹雪芹作品？",hl:"",word:"《红楼梦》·清代",meaning:"满纸荒唐言，一把辛酸泪",analogy:""},
  {front:"建安七子特征？",hl:"",word:"建安风骨",meaning:"慷慨悲凉，孔融陈琳等七人",analogy:""},
  {front:"《左传》体例？",hl:"",word:"编年体·春秋左氏传",meaning:"叙事之最，战争描写顶级",analogy:""},
  {front:"《战国策》体例？",hl:"",word:"国别体",meaning:"策士风采，说辞典范",analogy:""},
  {front:"《资治通鉴》作品？",hl:"",word:"司马光·编年体通史",meaning:"以史为鉴可知兴替",analogy:""},
];




const TEMPLATES = {
  A1:"诚然，[对立观点]在某种程度上具有其合理性，例如……；然而，如果我们审视其背后的深层逻辑，就会发现……",
  A2:"有人或许会主张：[对立观点]。这种看法并非全无道理，但它忽略了一个关键前提——……",
  A3:"站在[持方]的立场来看，[对立观点]确实有其依据。但当我们把视野放宽到[更大的层面]，就会发现……",
  A4:"不可否认，[对立观点]在[某个局限范围]内是成立的。然而，这恰恰暴露了它的盲区——……",
  B1:"这并非偶然的巧合，而是……的必然结果。究其本质，是因为……",
  B2:"事实上，[论点]不仅体现在[A层面]，更深刻地反映在[B层面]。二者的内在关联在于……",
  B3:"如果我们将[现象A]与[现象B]进行类比，就会发现它们在逻辑结构上共享一个核心特征——……",
  B4:"从更根本的层面来看，[论点]之所以成立，是因为它触及了一个被普遍忽略的前提——……",
  C1:"由此，我们不仅看到了……，更应当警惕其背后……的深层危机。",
  C2:"或许，最好的答案并不在于[二选一]，而在于我们在[更高维度]上寻得一种平衡——……",
  C3:"当我们重新审视[讨论的话题]时，会发现它最终指向了一个更本质的问题：我们究竟想要怎样的……？",
  C4:"归根结底，[论点]所关切的，不仅仅是……的问题，更关乎每一个人在[时代大背景]之中的安身立命。",
};


const BOOKS = [
  {rank:1,title:"《如何阅读一本书》",author:"莫提默·J·艾德勒",tag:"阅读",tagClass:"tag-read",desc:"西方阅读教学奠基。分析阅读规则直接套用现代文答题。"},
  {rank:2,title:"《批判性思维工具》",author:"理查德·保罗",tag:"阅读",tagClass:"tag-read",desc:"识别偏见、评估论证，攻克「作者观点辨析」高阶题型。"},
  {rank:3,title:"《他们说/我说》",author:"杰拉尔德·格拉夫",tag:"写作",tagClass:"tag-write",desc:"美高校通用写作教材，逻辑模板训练议论文起承转合。"},
  {rank:4,title:"《论证是一门学问》",author:"安东尼·威斯汀",tag:"写作",tagClass:"tag-write",desc:"极简论证规则手册。类比/因果/演绎论证可操作训练。"},
  {rank:5,title:"《写字留存》",author:"厄苏拉·勒古恩",tag:"写作",tagClass:"tag-write",desc:"语言节奏与细节，训练「展示不要陈述」的记叙文基本功。"},
  {rank:6,title:"《语法讲义》/《八百词》",author:"朱德熙/吕叔湘",tag:"语法",tagClass:"tag-grammar",desc:"结构主义语法，把汉语病句分析变成数学公式。"},
];




const GRAMMAR_EXAMPLES = [
  {sentence:"通过这次学习，使我认识到自己的不足。",
   analysis:"Step1 提主干：「通过这次学习」（介词结构→无主语）+「使」（谓）+「我」（宾）+「认识到…」（宾补）→ 全句缺少主语！\n\nStep2 配逻辑：介词「通过」导致主语被淹没=成分残缺（缺主语）\n修改①：去掉「通过」→「这次学习，使我认识到…」\n修改②：去掉「使」→「通过这次学习，我认识到…」\n\nStep3 规律：看到介词开头（通过/经过/由于/关于）立刻警惕缺主语！"},
  {sentence:"我们必须不断提高和培养自己的创新能力。",
   analysis:"Step1 提主干：我们（S）+提高和培养（V）+能力（O）→ 主干完整\n\nStep2 配逻辑：「提高……能力」✓；「培养……能力」✓ → 此句搭配正确\n\n💡 若改为「提高和培养水平」，则「培养水平」搭配不当，露出病句。"},
  {sentence:"这种做法，广为人民群众所欢迎。",
   analysis:"Step1 提主干：这种做法（S）+被欢迎（V）→ 主干完整\n\nStep2 配逻辑：「为……所……」是文言「为……所……」被动句式的残留。此句既用白话「广为」又用文言「为……所……」，属于句式杂糅。\n\nStep3 修改：「这种做法，受到人民群众的广泛欢迎。」"},
];




const RHETORIC_EXAMPLES = [
  {sentence:"风从巷子里灌出来，把纸角吹得一掀一掀的，像一只受伤的鸟在扑棱翅膀。",analysis:"📌 【高考标准答案示范】\n\n【第一步：明手法（1分）】\n运用了比喻（拟物）的手法，将「被风吹动的纸角」比作「受伤的鸟」。\n\n【第二步：析具体（2分）】\n结合语境，「一掀一掀」的动态与鸟「扑棱翅膀」的挣扎感相重合，生动形象地写出了纸角在风中无助、颤抖的物理形态。\n\n【第三步：阐效果（2分）】\n通过「受伤的鸟」这一具有痛感的意象，寄托并外化了人物此时内心挣扎、焦虑、脆弱的心理状态，达到了景情交融的效果。"},
  {sentence:"指点江山，激扬文字，粪土当年万户侯。",analysis:"📌 【高考标准答案示范】\n\n【第一步：明手法（1分）】\n运用了借代与对偶的手法。「江山」代指国家政权，「文字」代指革命舆论。\n\n【第二步：析具体（2分）】\n「指点」与「激扬」相对，「江山」与「文字」并列，句式整齐，音韵和谐，在对比中使革命活动更显具象化。\n\n【第三步：阐效果（2分）】\n借代的使用化抽象为具体，增强了形象性；对偶则让语言节奏感极强，慷慨激昂地表现出青年革命者蔑视权贵、担当天下的豪迈气概。"},
  {sentence:"他们的品质是那样的纯洁和高尚，他们的意志是那样的坚韧和刚强，他们的气质是那样的淳朴和谦逊……",analysis:"📌 【高考标准答案示范】\n\n【第一步：明手法（1分）】\n运用了排比的手法。连续三个「他们的……是那样的……」句式相同、语气一致。\n\n【第二步：析具体（2分）】\n从「品质」、「意志」、「气质」三个不同维度，层层递进地铺陈志愿军战士的高尚精神内核，形成了排山倒海的语势。\n\n【第三步：阐效果（2分）】\n结构整齐，音律顺畅，增强了文章的抒情气势，强烈地表达了作者对战士们无以复加的崇敬与赞美之情。"}
];




const NOVEL_EXAMPLES = [
  {title:"视角：第一人称限制视角的妙用",analysis:"📌 【叙事视角·高考答题模板】\n\n【第一步：判视角（1分）】\n本文采用第一人称（「我」）的限制性视角展开叙事。\n\n【第二步：析效果（2分）】\n1. 真实与拉近感：「我」作为故事的见证者与亲历者，具有极强的真实感。\n2. 制造悬念：由于「我」的认知局限性，无法窥见其他人物的完整心理，为情节发展设置了多处悬念。\n\n【第三步：扣主旨（1分）】\n通过「我」的主观感受和视线的推移，展现出普通人在特定时代环境下的心理波澜。"},
  {title:"时空：双线穿插与插叙的张力",analysis:"📌 【叙事结构·高考答题模板】\n\n【第一步：明手法（1分）】\n运用了「双线交织」与「插叙」相结合的叙事结构。\n\n【第二步：析具体（2分）】\n1. 明暗双线：以明线（主人公眼前的等待过程）推动现实时间；以暗线（插叙过去的遭遇和真相）揭示前因后果。\n2. 插叙切入：适时穿插往日的回忆，打破了单一时间轴的平铺直叙。\n\n【第三步：阐效果（2分）】\n这种叙事时空的交错，极大地丰富了小说的情节容量，强化了小说的戏剧冲突。"},
  {title:"道具：核心物象的结构与象征作用",analysis:"📌 【道具/物象·高考答题模板】\n\n【第一步：析物理（1分）】\n「对折的纸」是贯穿全文的核心线索与道具（物象）。\n\n【第二步：析结构（2分）】\n1. 线索作用：小说以「纸」的出现开篇，中途写「纸」在风中的挣扎，串联起承转合。\n2. 制造冲突：这张未打开的纸成为了情节的暴风眼。\n\n【第三步：析象征（2分）】\n1. 象征意义：纸上的字虽未点明，但其在风中「像受伤的鸟」一样挣扎，象征着主人公破碎的内心世界。\n2. 深化主题：道具的反复出现，将抽象的情感具象化。"}
];




const READING_PASSAGES = [
  {
    id: 'rc1', title: '信息类文本 · 人工智能与教育',
    passage: '人工智能正在重塑教育生态。一方面，个性化学习系统可以根据学生的认知水平定制内容，让每个学生都能以适合自己的节奏前进；另一方面，过度依赖算法推荐可能导致"信息茧房"，使学生只能接触自己舒适区内的知识，失去探索未知领域的机会。因此，技术赋能教育的关键不在于技术本身有多先进，而在于我们如何设计"人机协作"的教育生态。当前，一些学校尝试将AI助教引入课堂，由AI负责知识点的讲解与练习推送，教师则专注于情感互动和创造性思维的引导。这种分工模式既发挥了AI在数据处理和个性化推荐上的优势，又保留了教育中不可替代的"人的温度"。不过，也有学者担忧，如果教师过度依赖AI系统，可能会逐渐丧失课程设计的主导权，使教育沦为"算法驱动"而非"理念驱动"。',
    questions: [
      { q: '1. 根据原文，下列关于"技术赋能教育"的理解，正确的一项是（3分）',
        options: ['A. 技术越先进，教育效果就越好', 'B. 技术赋能的关键在于设计人机协作的生态', 'C. AI可以完全替代教师的全部工作', 'D. 算法推荐必然导致信息茧房'],
        answer: 1 },
      { q: '2. 文中提到的"AI助教+教师"分工模式，下列表述不符合原文的一项是（3分）',
        options: ['A. AI负责知识点讲解与练习推送', 'B. 教师专注于情感互动与创造性思维引导', 'C. 该模式完全消除了AI的局限性', 'D. 保留教育中不可替代的"人的温度"'],
        answer: 2 },
      { q: '3. 关于学者对AI教育的担忧，下列说法正确的一项是（3分）',
        options: ['A. 学者认为AI不应进入课堂', 'B. 教师过度依赖AI可能丧失课程设计主导权', 'C. AI已经使教育沦为算法驱动', 'D. 教育不应该使用任何技术手段'],
        answer: 1 }
    ]
  },
  {
    id: 'rc2', title: '文学类文本 · 巷口的等待',
    passage: '他站在巷口，手里攥着一张对折的纸。风从巷子里灌出来，把纸角吹得一掀一掀的，像一只受伤的鸟在扑棱翅膀。他没有打开它——他已经看了太多遍。那些字像是用针尖划在纸面上的，每一个都扎眼睛。他只是在等，等巷子尽头那扇门打开，或者永远不开。暮色渐渐漫上来，巷子里亮起几盏昏黄的灯，把人影拉得又细又长。远处隐约传来饭菜的香味，和孩子们的嬉闹声。他依然站着，像一棵被遗忘在墙角的枯树。',
    questions: [
      { q: '1. 下列对文中比喻手法的赏析，不正确的一项是（3分）',
        options: ['A. "像一只受伤的鸟在扑棱翅膀"以动作写焦虑', 'B. "像用针尖划在纸面上"以痛觉写视觉冲击', 'C. "像一棵被遗忘在墙角的枯树"暗示人物身份卑微', 'D. 三个比喻均服务于人物心理刻画'],
        answer: 2 },
      { q: '2. 关于文中环境描写的作用，分析正确的一项是（3分）',
        options: ['A. 暮色和灯光渲染了温馨的家庭氛围', 'B. 远处饭菜香与嬉闹声暗示人物已放弃等待', 'C. 环境以"暖"衬"冷"，反衬人物的孤独与坚持', 'D. 环境描写仅作为时间推移的交代'],
        answer: 2 },
      { q: '3. 下列对全文主旨的理解，最准确的一项是（3分）',
        options: ['A. 赞美了民间巷弄的生活气息', 'B. 批评了现代人缺乏耐心的等待', 'C. 通过"等待"这一动作写出了希望与绝望的张力', 'D. 呼吁人们珍惜身边的亲情'],
        answer: 2 }
    ]
  },
  {
    id: 'rc3', title: '论述类文本 · 经典阅读的价值',
    passage: '经典之所以为经典，不在于它完美无瑕，而在于它能够持续地与不同时代的读者对话。一部《论语》，两千年来被无数人解读、质疑、再解读，每一次对话都丰富了文本的生命而非消耗它。这正是卡尔维诺所说的："经典是那些你经常听人家说\'我正在重读……\'而不是\'我正在读……\'的书。"然而，在信息爆炸的今天，浅阅读和碎片化阅读正在侵蚀经典的生存空间。有调查显示，超过六成的受访大学生表示"没有完整读过一部经典名著"。这其中固然有时间碎片化的客观原因，但更深层的问题在于：当"快"成为时代精神，"慢"阅读就成了一种奢侈。值得注意的是，经典阅读的价值恰恰在于它的"慢"——它要求读者放慢节奏，深入思考，与文本展开真正的对话。这种"慢"，不是效率的敌人，而是深度理解的必要条件。',
    questions: [
      { q: '1. 下列关于原文内容的理解和分析，正确的一项是（3分）',
        options: ['A. 经典之所以为经典，是因为它完美无瑕', 'B. 对经典的解读会消耗文本的生命力', 'C. 卡尔维诺认为经典是值得反复重读的书', 'D. 经典阅读是效率的敌人'],
        answer: 2 },
      { q: '2. 下列对原文论证的相关分析，不正确的一项是（3分）',
        options: ['A. 引用卡尔维诺的话是为了定义经典', 'B. 用调查数据论证浅阅读现象的存在', 'C. 将"快"与"慢"对举突出经典阅读的价值', 'D. 文章否定了碎片化阅读的一切价值'],
        answer: 3 },
      { q: '3. 根据原文，"慢"阅读的含义是（3分）',
        options: ['A. 阅读速度缓慢', 'B. 放慢节奏，深入思考，与文本展开对话', 'C. 拒绝一切电子阅读', 'D. 每天只读一页书'],
        answer: 1 }
    ]
  }
];

const DECK_GAOZHONG = [
  {"front": "学不可以已", "hl": "已", "word": "已", "meaning": "停止", "analogy": "★《劝学》"},
  {"front": "木直中绳，其曲中规", "hl": "中", "word": "中(zhòng)", "meaning": "合乎", "analogy": "★《劝学》"},
  {"front": "虽有槁暴，不复挺者", "hl": "挺", "word": "挺", "meaning": "直", "analogy": "★《劝学》"},
  {"front": "君子生非异也，善假于物也", "hl": "假", "word": "假", "meaning": "借助", "analogy": "★《劝学》"},
  {"front": "假舟楫者，非能水也，而绝江河", "hl": "绝", "word": "绝", "meaning": "横渡", "analogy": "★《劝学》"},
  {"front": "锲而不舍，金石可镂", "hl": "镂", "word": "镂", "meaning": "雕刻", "analogy": "★《劝学》"},
  {"front": "古之学者必有师 / 吾从而师之", "hl": "师", "word": "师", "meaning": "老师/以……为师", "analogy": "★《师说》"},
  {"front": "师者，所以传道受业解惑也", "hl": "受", "word": "受", "meaning": "通「授」,传授", "analogy": "★《师说》"},
  {"front": "人非生而知之者，孰能无惑", "hl": "惑", "word": "惑", "meaning": "疑惑", "analogy": "★《师说》"},
  {"front": "巫医乐师百工之人，君子不齿", "hl": "不齿", "word": "不齿", "meaning": "看不起", "analogy": "★《师说》"},
  {"front": "术业有专攻", "hl": "术业", "word": "术业", "meaning": "学术技艺", "analogy": "★《师说》"},
  {"front": "壬戌之秋，七月既望", "hl": "既望", "word": "既望", "meaning": "农历每月十六日", "analogy": "★《赤壁赋》"},
  {"front": "举酒属客，诵明月之诗", "hl": "属", "word": "属(zhǔ)", "meaning": "劝请", "analogy": "★《赤壁赋》"},
  {"front": "纵一苇之所如，凌万顷之茫然", "hl": "如", "word": "如", "meaning": "往", "analogy": "★《赤壁赋》"},
  {"front": "苏子愀然，正襟危坐", "hl": "愀然", "word": "愀(qiǎo)然", "meaning": "容色改变的样子", "analogy": "★《赤壁赋》"},
  {"front": "是造物者之无尽藏也，而吾与子之所共适", "hl": "适", "word": "适", "meaning": "享有", "analogy": "★《赤壁赋》"},
  {"front": "泰山之阳，汶水西流；其阴，济水东流", "hl": "阳/阴", "word": "阳/阴", "meaning": "山南/山北", "analogy": "★《登泰山记》"},
  {"front": "自京师乘风雪，历齐河、长清", "hl": "乘", "word": "乘", "meaning": "冒着", "analogy": "★《登泰山记》"},
  {"front": "越长城之限，至于泰安", "hl": "限", "word": "限", "meaning": "界限/门槛", "analogy": "★《登泰山记》"},
  {"front": "苍山负雪，明烛天南", "hl": "烛", "word": "烛", "meaning": "照", "analogy": "★《登泰山记》"},
  {"front": "戊申晦，五鼓，与子颍坐日观亭", "hl": "晦", "word": "晦", "meaning": "农历每月最后一天", "analogy": "★《登泰山记》"},
  {"front": "对酒当歌，人生几何", "hl": "几何", "word": "几何", "meaning": "多少", "analogy": "★《短歌行》"},
  {"front": "越陌度阡，枉用相存", "hl": "存", "word": "存", "meaning": "问候、探望", "analogy": "★《短歌行》"},
  {"front": "山不厌高，海不厌深", "hl": "厌", "word": "厌", "meaning": "满足", "analogy": "★《短歌行》"},
  {"front": "少无适俗韵，性本爱丘山", "hl": "韵", "word": "韵", "meaning": "气质、情致", "analogy": "★《归园田居》"},
  {"front": "开荒南野际，守拙归园田", "hl": "守拙", "word": "守拙", "meaning": "持守愚拙本性", "analogy": "★《归园田居》"},
  {"front": "海客谈瀛洲，烟涛微茫信难求", "hl": "信", "word": "信", "meaning": "实在", "analogy": "★《梦游天姥吟留别》"},
  {"front": "势拔五岳掩赤城", "hl": "拔", "word": "拔", "meaning": "超出", "analogy": "★《梦游天姥吟留别》"},
  {"front": "熊咆龙吟殷岩泉", "hl": "殷", "word": "殷(yǐn)", "meaning": "震动", "analogy": "★《梦游天姥吟留别》"},
  {"front": "予左迁九江郡司马", "hl": "左迁", "word": "左迁", "meaning": "降职", "analogy": "★《琵琶行》"},
  {"front": "年长色衰，委身为贾人妇", "hl": "委身", "word": "委身", "meaning": "嫁人", "analogy": "★《琵琶行》"},
  {"front": "低眉信手续续弹，说尽心中无限事", "hl": "信手", "word": "信手", "meaning": "随手", "analogy": "★《琵琶行》"},
  {"front": "人生如梦，一尊还酹江月", "hl": "酹", "word": "酹(lèi)", "meaning": "洒酒祭奠", "analogy": "★《念奴娇》"},
  {"front": "今齐地方千里", "hl": "地方", "word": "地方(古)", "meaning": "土地/方圆", "analogy": "★古今异义"},
  {"front": "未尝不叹息痛恨于桓、灵也", "hl": "痛恨", "word": "痛恨(古)", "meaning": "痛心/遗憾", "analogy": "★古今异义"},
  {"front": "乃不知有汉，无论魏晋", "hl": "无论", "word": "无论(古)", "meaning": "不要说", "analogy": "★古今异义"},
  {"front": "因为长句，歌以赠之", "hl": "因为", "word": "因为(古)", "meaning": "因此/创作", "analogy": "★古今异义"},
];

const DECK_GZSHICI = [
  {"front": "学不可以已", "hl": "已", "word": "已", "meaning": "停止", "analogy": "★《劝学》"},
  {"front": "木直中绳，其曲中规", "hl": "中", "word": "中(zhòng)", "meaning": "合乎", "analogy": "★《劝学》"},
  {"front": "虽有槁暴，不复挺者", "hl": "挺", "word": "挺", "meaning": "直", "analogy": "★《劝学》"},
  {"front": "君子生非异也，善假于物也", "hl": "假", "word": "假", "meaning": "借助", "analogy": "★《劝学》"},
  {"front": "假舟楫者，非能水也，而绝江河", "hl": "绝", "word": "绝", "meaning": "横渡", "analogy": "★《劝学》"},
  {"front": "锲而不舍，金石可镂", "hl": "镂", "word": "镂", "meaning": "雕刻", "analogy": "★《劝学》"},
  {"front": "古之学者必有师 / 吾从而师之", "hl": "师", "word": "师", "meaning": "老师/以……为师", "analogy": "★《师说》"},
  {"front": "师者，所以传道受业解惑也", "hl": "受", "word": "受", "meaning": "通「授」,传授", "analogy": "★《师说》"},
  {"front": "人非生而知之者，孰能无惑", "hl": "惑", "word": "惑", "meaning": "疑惑", "analogy": "★《师说》"},
  {"front": "巫医乐师百工之人，君子不齿", "hl": "不齿", "word": "不齿", "meaning": "看不起", "analogy": "★《师说》"},
  {"front": "术业有专攻", "hl": "术业", "word": "术业", "meaning": "学术技艺", "analogy": "★《师说》"},
  {"front": "壬戌之秋，七月既望", "hl": "既望", "word": "既望", "meaning": "农历每月十六日", "analogy": "★《赤壁赋》"},
  {"front": "举酒属客，诵明月之诗", "hl": "属", "word": "属(zhǔ)", "meaning": "劝请", "analogy": "★《赤壁赋》"},
  {"front": "纵一苇之所如，凌万顷之茫然", "hl": "如", "word": "如", "meaning": "往", "analogy": "★《赤壁赋》"},
  {"front": "苏子愀然，正襟危坐", "hl": "愀然", "word": "愀(qiǎo)然", "meaning": "容色改变的样子", "analogy": "★《赤壁赋》"},
  {"front": "是造物者之无尽藏也，而吾与子之所共适", "hl": "适", "word": "适", "meaning": "享有", "analogy": "★《赤壁赋》"},
  {"front": "泰山之阳，汶水西流；其阴，济水东流", "hl": "阳/阴", "word": "阳/阴", "meaning": "山南/山北", "analogy": "★《登泰山记》"},
  {"front": "自京师乘风雪，历齐河、长清", "hl": "乘", "word": "乘", "meaning": "冒着", "analogy": "★《登泰山记》"},
  {"front": "越长城之限，至于泰安", "hl": "限", "word": "限", "meaning": "界限/门槛", "analogy": "★《登泰山记》"},
  {"front": "苍山负雪，明烛天南", "hl": "烛", "word": "烛", "meaning": "照", "analogy": "★《登泰山记》"},
  {"front": "戊申晦，五鼓，与子颍坐日观亭", "hl": "晦", "word": "晦", "meaning": "农历每月最后一天", "analogy": "★《登泰山记》"},
  {"front": "对酒当歌，人生几何", "hl": "几何", "word": "几何", "meaning": "多少", "analogy": "★《短歌行》"},
  {"front": "越陌度阡，枉用相存", "hl": "存", "word": "存", "meaning": "问候、探望", "analogy": "★《短歌行》"},
  {"front": "山不厌高，海不厌深", "hl": "厌", "word": "厌", "meaning": "满足", "analogy": "★《短歌行》"},
  {"front": "少无适俗韵，性本爱丘山", "hl": "韵", "word": "韵", "meaning": "气质、情致", "analogy": "★《归园田居》"},
  {"front": "开荒南野际，守拙归园田", "hl": "守拙", "word": "守拙", "meaning": "持守愚拙本性", "analogy": "★《归园田居》"},
  {"front": "海客谈瀛洲，烟涛微茫信难求", "hl": "信", "word": "信", "meaning": "实在", "analogy": "★《梦游天姥吟留别》"},
  {"front": "势拔五岳掩赤城", "hl": "拔", "word": "拔", "meaning": "超出", "analogy": "★《梦游天姥吟留别》"},
  {"front": "熊咆龙吟殷岩泉", "hl": "殷", "word": "殷(yǐn)", "meaning": "震动", "analogy": "★《梦游天姥吟留别》"},
  {"front": "予左迁九江郡司马", "hl": "左迁", "word": "左迁", "meaning": "降职", "analogy": "★《琵琶行》"},
  {"front": "年长色衰，委身为贾人妇", "hl": "委身", "word": "委身", "meaning": "嫁人", "analogy": "★《琵琶行》"},
  {"front": "低眉信手续续弹，说尽心中无限事", "hl": "信手", "word": "信手", "meaning": "随手", "analogy": "★《琵琶行》"},
  {"front": "人生如梦，一尊还酹江月", "hl": "酹", "word": "酹(lèi)", "meaning": "洒酒祭奠", "analogy": "★《念奴娇》"},
  {"front": "今齐地方千里", "hl": "地方", "word": "地方(古)", "meaning": "土地/方圆", "analogy": "★古今异义"},
  {"front": "未尝不叹息痛恨于桓、灵也", "hl": "痛恨", "word": "痛恨(古)", "meaning": "痛心/遗憾", "analogy": "★古今异义"},
  {"front": "乃不知有汉，无论魏晋", "hl": "无论", "word": "无论(古)", "meaning": "不要说", "analogy": "★古今异义"},
  {"front": "因为长句，歌以赠之", "hl": "因为", "word": "因为(古)", "meaning": "因此/创作", "analogy": "★古今异义"},
  {"front": "屈平疾王听之不聪也", "hl": "疾", "word": "疾", "meaning": "痛心", "analogy": "★《屈原列传》"},
  {"front": "人穷则反本，故劳苦倦极，未尝不呼天也", "hl": "反本", "word": "反本", "meaning": "追念根本", "analogy": "★《屈原列传》"},
  {"front": "信而见疑，忠而被谤，能无怨乎？", "hl": "见", "word": "见", "meaning": "被", "analogy": "★《屈原列传》"},
  {"front": "其文约，其辞微，其志洁，其行廉", "hl": "约", "word": "约", "meaning": "简约", "analogy": "★《屈原列传》"},
  {"front": "皭然泥而不滓者也", "hl": "泥", "word": "泥", "meaning": "染黑", "analogy": "★《屈原列传》"},
  {"front": "明年，秦割汉中地与楚以和", "hl": "明年", "word": "明年", "meaning": "第二年", "analogy": "★《屈原列传》"},
  {"front": "而设诡辩于怀王之宠姬郑袖", "hl": "诡辩", "word": "诡辩", "meaning": "说假话", "analogy": "★《屈原列传》"},
  {"front": "被发行吟泽畔，颜色憔悴", "hl": "颜色", "word": "颜色(古)", "meaning": "脸色", "analogy": "★《屈原列传》"},
  {"front": "颜色憔悴，形容枯槁", "hl": "形容", "word": "形容(古)", "meaning": "形体容貌", "analogy": "★《屈原列传》"},
  {"front": "匈奴使来，汉亦留之以相当", "hl": "相当", "word": "相当(古)", "meaning": "相抵", "analogy": "★《苏武传》"},
  {"front": "武帝嘉其义", "hl": "嘉", "word": "嘉", "meaning": "赞许", "analogy": "★《苏武传》"},
  {"front": "虞常在汉时，素与副张胜相知", "hl": "相知", "word": "相知", "meaning": "熟识", "analogy": "★《苏武传》"},
  {"front": "见犯乃死，重负国", "hl": "见犯", "word": "见犯", "meaning": "受到侮辱", "analogy": "★《苏武传》"},
  {"front": "见犯乃死，重负国", "hl": "重", "word": "重", "meaning": "更加", "analogy": "★《苏武传》"},
  {"front": "虞常果引张胜", "hl": "引", "word": "引", "meaning": "牵扯", "analogy": "★《苏武传》"},
  {"front": "单于壮其节", "hl": "壮", "word": "壮", "meaning": "以……为壮", "analogy": "★《苏武传》"},
  {"front": "副有罪，当相坐", "hl": "坐", "word": "坐", "meaning": "连坐", "analogy": "★《苏武传》"},
  {"front": "复举剑拟之，武不动", "hl": "拟", "word": "拟", "meaning": "比画", "analogy": "★《苏武传》"},
  {"front": "武卧啮雪，与旃毛并咽之", "hl": "啮", "word": "啮", "meaning": "咬/嚼", "analogy": "★《苏武传》"},
  {"front": "使牧羝，羝乳乃得归", "hl": "乳", "word": "乳", "meaning": "生子", "analogy": "★《苏武传》"},
  {"front": "皆为陛下所成就", "hl": "成就", "word": "成就(古)", "meaning": "栽培/提拔", "analogy": "★《苏武传》"},
  {"front": "秦孝公据崤函之固", "hl": "固", "word": "固", "meaning": "险要地势", "analogy": "★《过秦论》"},
  {"front": "诸侯恐惧，会盟而谋弱秦", "hl": "弱", "word": "弱", "meaning": "削弱", "analogy": "★《过秦论》"},
  {"front": "不爱珍器重宝肥饶之地", "hl": "爱", "word": "爱", "meaning": "吝惜", "analogy": "★《过秦论》"},
  {"front": "以致天下之士，合从缔交", "hl": "致", "word": "致", "meaning": "招纳", "analogy": "★《过秦论》"},
  {"front": "追亡逐北，伏尸百万", "hl": "北", "word": "北", "meaning": "败逃的军队", "analogy": "★《过秦论》"},
  {"front": "振长策而御宇内", "hl": "御", "word": "御", "meaning": "驾驭/统治", "analogy": "★《过秦论》"},
  {"front": "履至尊而制六合", "hl": "履", "word": "履", "meaning": "登上", "analogy": "★《过秦论》"},
  {"front": "却匈奴七百余里", "hl": "却", "word": "却", "meaning": "使……退却", "analogy": "★《过秦论》"},
  {"front": "隳名城，杀豪杰", "hl": "隳", "word": "隳(huī)", "meaning": "毁坏", "analogy": "★《过秦论》"},
  {"front": "斩木为兵，揭竿为旗", "hl": "揭", "word": "揭", "meaning": "举", "analogy": "★《过秦论》"},
  {"front": "赢粮而景从", "hl": "景", "word": "景", "meaning": "同「影」", "analogy": "★《过秦论》"},
  {"front": "天下云集响应", "hl": "云/响", "word": "云/响", "meaning": "名词作状语", "analogy": "★《过秦论》"},
  {"front": "原庄宗之所以得天下", "hl": "原", "word": "原", "meaning": "推其根本", "analogy": "★《伶官传序》"},
  {"front": "方其系燕父子以组", "hl": "系", "word": "系", "meaning": "捆绑", "analogy": "★《伶官传序》"},
  {"front": "函梁君臣之首", "hl": "函", "word": "函", "meaning": "用匣子装", "analogy": "★《伶官传序》"},
  {"front": "抑本其成败之迹", "hl": "抑", "word": "抑", "meaning": "或者", "analogy": "★《伶官传序》"},
  {"front": "抑本其成败之迹", "hl": "本", "word": "本", "meaning": "探究", "analogy": "★《伶官传序》"},
  {"front": "因而和焉", "hl": "和", "word": "和(hè)", "meaning": "酬答", "analogy": "★《燕歌行》"},
  {"front": "旌旆逶迤碣石间", "hl": "逶迤", "word": "逶迤(wēiyí)", "meaning": "舒展", "analogy": "★《燕歌行》"},
  {"front": "绝域苍茫无所有", "hl": "绝域", "word": "绝域", "meaning": "极远的地方", "analogy": "★《燕歌行》"},
  {"front": "吴丝蜀桐张高秋", "hl": "张", "word": "张", "meaning": "弹奏", "analogy": "★《李凭箜篌引》"},
  {"front": "锦瑟无端五十弦", "hl": "无端", "word": "无端", "meaning": "无缘无故", "analogy": "★《锦瑟》"},
  {"front": "早岁那知世事艰", "hl": "那", "word": "那", "meaning": "哪", "analogy": "★《书愤》"},
  {"front": "氓之蚩蚩，抱布贸丝", "hl": "贸", "word": "贸", "meaning": "交易", "analogy": "★《氓》"},
  {"front": "匪来贸丝，来即我谋", "hl": "即", "word": "即", "meaning": "靠近/商量", "analogy": "★《氓》"},
  {"front": "匪我愆期，子无良媒", "hl": "愆", "word": "愆(qiān)", "meaning": "拖延", "analogy": "★《氓》"},
  {"front": "将子无怒，秋以为期", "hl": "将", "word": "将(qiāng)", "meaning": "愿/请", "analogy": "★《氓》"},
  {"front": "于嗟女兮，无与士耽", "hl": "耽", "word": "耽", "meaning": "沉溺", "analogy": "★《氓》"},
  {"front": "女之耽兮，不可说也", "hl": "说", "word": "说", "meaning": "同「脱」,脱身", "analogy": "★《氓》"},
  {"front": "自我徂尔，三岁食贫", "hl": "徂", "word": "徂(cú)", "meaning": "往", "analogy": "★《氓》"},
  {"front": "女也不爽，士贰其行", "hl": "爽", "word": "爽", "meaning": "差错", "analogy": "★《氓》"},
  {"front": "士贰其行", "hl": "贰", "word": "贰", "meaning": "不专一", "analogy": "★《氓》"},
  {"front": "帝高阳之苗裔兮", "hl": "苗裔", "word": "苗裔", "meaning": "后代", "analogy": "★《离骚》"},
  {"front": "皇览揆余初度兮", "hl": "揆", "word": "揆(kuí)", "meaning": "测量/衡量", "analogy": "★《离骚》"},
  {"front": "肇锡余以嘉名", "hl": "肇", "word": "肇(zhào)", "meaning": "开始", "analogy": "★《离骚》"},
  {"front": "春与秋其代序", "hl": "代序", "word": "代序", "meaning": "时序更替", "analogy": "★《离骚》"},
  {"front": "謇朝谇而夕替", "hl": "替", "word": "替", "meaning": "废弃", "analogy": "★《离骚》"},
  {"front": "忍尤而攘诟", "hl": "尤", "word": "尤", "meaning": "责备", "analogy": "★《离骚》"},
  {"front": "为仲卿母所遣", "hl": "遣", "word": "遣", "meaning": "夫家休弃妻子", "analogy": "★《孔雀东南飞》"},
  {"front": "便可白公姥", "hl": "白", "word": "白", "meaning": "告诉/禀告", "analogy": "★《孔雀东南飞》"},
  {"front": "谢家来贵门", "hl": "谢", "word": "谢", "meaning": "辞别", "analogy": "★《孔雀东南飞》"},
  {"front": "始适还家门", "hl": "适", "word": "适", "meaning": "出嫁", "analogy": "★《孔雀东南飞》"},
  {"front": "便言多令才", "hl": "令", "word": "令", "meaning": "美好", "analogy": "★《孔雀东南飞》"},
  {"front": "可以横绝峨眉巅", "hl": "绝", "word": "绝", "meaning": "横越", "analogy": "★《蜀道难》"},
  {"front": "上有六龙回日之高标", "hl": "回", "word": "回", "meaning": "回转", "analogy": "★《蜀道难》"},
  {"front": "使人听此凋朱颜", "hl": "凋", "word": "凋", "meaning": "使……凋谢", "analogy": "★《蜀道难》"},
  {"front": "连峰去天不盈尺", "hl": "去", "word": "去", "meaning": "距离", "analogy": "★《蜀道难》"},
  {"front": "臣以险衅，夙遭闵凶", "hl": "险衅", "word": "险衅(xìnxìn)", "meaning": "艰难祸患", "analogy": "★《陈情表》"},
  {"front": "慈父见背", "hl": "见背", "word": "见背", "meaning": "指尊长去世", "analogy": "★《陈情表》"},
  {"front": "终鲜兄弟", "hl": "鲜", "word": "鲜(xiǎn)", "meaning": "少/没有", "analogy": "★《陈情表》"},
  {"front": "而刘夙婴疾病", "hl": "婴", "word": "婴", "meaning": "缠绕", "analogy": "★《陈情表》"},
  {"front": "除臣洗马", "hl": "除", "word": "除", "meaning": "授官", "analogy": "★《陈情表》"},
  {"front": "则刘病日笃", "hl": "笃", "word": "笃(dǔ)", "meaning": "病重", "analogy": "★《陈情表》"},
  {"front": "过蒙拔擢", "hl": "拔擢", "word": "拔擢(bá zhuó)", "meaning": "提拔", "analogy": "★《陈情表》"},
  {"front": "日薄西山", "hl": "薄", "word": "薄", "meaning": "迫近", "analogy": "★《陈情表》"},
  {"front": "余稍为修葺", "hl": "修葺", "word": "修葺(xiūqì)", "meaning": "修补", "analogy": "★《项脊轩志》"},
  {"front": "室始洞然", "hl": "洞然", "word": "洞然", "meaning": "明亮的样子", "analogy": "★《项脊轩志》"},
  {"front": "迨诸父异爨", "hl": "异爨", "word": "异爨(yìcuàn)", "meaning": "分家", "analogy": "★《项脊轩志》"},
  {"front": "乳二世", "hl": "乳", "word": "乳", "meaning": "哺育", "analogy": "★《项脊轩志》"},
  {"front": "吾妻归宁", "hl": "归宁", "word": "归宁", "meaning": "女子回娘家省亲", "analogy": "★《项脊轩志》"},
  {"front": "今已亭亭如盖矣", "hl": "盖", "word": "盖", "meaning": "伞盖", "analogy": "★《项脊轩志》"},
  {"front": "群贤毕至", "hl": "毕", "word": "毕", "meaning": "全/都", "analogy": "★《兰亭集序》"},
  {"front": "茂林修竹", "hl": "修", "word": "修", "meaning": "高", "analogy": "★《兰亭集序》"},
  {"front": "列坐其次", "hl": "次", "word": "次", "meaning": "旁边", "analogy": "★《兰亭集序》"},
  {"front": "信可乐也", "hl": "信", "word": "信", "meaning": "实在", "analogy": "★《兰亭集序》"},
  {"front": "若合一契", "hl": "契", "word": "契(qì)", "meaning": "符契", "analogy": "★《兰亭集序》"},
  {"front": "一死生为虚诞", "hl": "一", "word": "一", "meaning": "把……看作一样", "analogy": "★《兰亭集序》"},
  {"front": "悟已往之不谏", "hl": "谏", "word": "谏", "meaning": "挽回", "analogy": "★《归去来兮辞》"},
  {"front": "知来者之可追", "hl": "追", "word": "追", "meaning": "补救", "analogy": "★《归去来兮辞》"},
  {"front": "三径就荒", "hl": "就", "word": "就", "meaning": "荒芜", "analogy": "★《归去来兮辞》"},
  {"front": "眄庭柯以怡颜", "hl": "眄", "word": "眄(miǎn)", "meaning": "看", "analogy": "★《归去来兮辞》"},
  {"front": "云无心以出岫", "hl": "岫", "word": "岫(xiù)", "meaning": "山峰", "analogy": "★《归去来兮辞》"},
  {"front": "曷不委心任去留", "hl": "委心", "word": "委心", "meaning": "随心所欲", "analogy": "★《归去来兮辞》"},
  {"front": "驼业种树", "hl": "业", "word": "业", "meaning": "以……为业", "analogy": "★《种树郭橐驼传》"},
  {"front": "早实以蕃", "hl": "蕃", "word": "蕃(fán)", "meaning": "多", "analogy": "★《种树郭橐驼传》"},
  {"front": "以致其性焉尔", "hl": "致", "word": "致", "meaning": "使达到", "analogy": "★《种树郭橐驼传》"},
  {"front": "字而幼孩", "hl": "字", "word": "字", "meaning": "养育", "analogy": "★《种树郭橐驼传》"},
  {"front": "遂而鸡豚", "hl": "遂", "word": "遂", "meaning": "成/养好", "analogy": "★《种树郭橐驼传》"},
  {"front": "微风鼓浪", "hl": "鼓", "word": "鼓", "meaning": "激荡", "analogy": "★《石钟山记》"},
  {"front": "余自齐安舟行适临汝", "hl": "适", "word": "适", "meaning": "往", "analogy": "★《石钟山记》"},
  {"front": "汝识之乎", "hl": "识", "word": "识(zhì)", "meaning": "知道", "analogy": "★《石钟山记》"},
  {"front": "痴儿了却公家事", "hl": "了却", "word": "了却", "meaning": "办完", "analogy": "★《登快阁》"},
  {"front": "夜雪初霁", "hl": "霁", "word": "霁(jì)", "meaning": "天刚晴", "analogy": "★《临安春雨初霁》"},
  {"front": "晴窗细乳戏分茶", "hl": "分茶", "word": "分茶", "meaning": "宋代烹茶法", "analogy": "★《临安春雨初霁》"},
  {"front": "敏于事而慎于言", "hl": "敏", "word": "敏", "meaning": "勤勉", "analogy": "★《论语》"},
  {"front": "就有道而正焉", "hl": "就有道", "word": "就有道", "meaning": "到有道的人那里去", "analogy": "★《论语》"},
  {"front": "君子喻于义，小人喻于利", "hl": "喻", "word": "喻", "meaning": "知晓、明白", "analogy": "★《论语》"},
  {"front": "见贤思齐焉", "hl": "齐", "word": "齐", "meaning": "等同", "analogy": "★《论语》"},
  {"front": "质胜文则野，文胜质则史", "hl": "质/文/野/史", "word": "质文野史", "meaning": "质朴/文采/粗野/虚浮", "analogy": "★《论语》"},
  {"front": "士不可以不弘毅", "hl": "弘毅", "word": "弘毅", "meaning": "志向远大，意志坚强", "analogy": "★《论语》"},
  {"front": "譬如为山，未成一篑", "hl": "一篑", "word": "一篑", "meaning": "一筐土", "analogy": "★《论语》"},
  {"front": "克己复礼为仁", "hl": "克己复礼", "word": "克己复礼", "meaning": "约束自我，归复于礼", "analogy": "★《论语》"},
  {"front": "回虽不敏，请事斯语矣", "hl": "事", "word": "事", "meaning": "实践、从事", "analogy": "★《论语》"},
  {"front": "《诗》可以兴，可以观，可以群，可以怨", "hl": "兴观群怨", "word": "兴观群怨", "meaning": "激发/观察/合群/怨刺", "analogy": "★《论语》"},
  {"front": "大学之道，在明明德", "hl": "明明德", "word": "明明德", "meaning": "彰明美德", "analogy": "★《大学》"},
  {"front": "在止于至善 / 知止而后有定", "hl": "止", "word": "止", "meaning": "达到/停止", "analogy": "★《大学》"},
  {"front": "安而后能虑，虑而后能得", "hl": "虑", "word": "虑", "meaning": "思虑精详", "analogy": "★《大学》"},
  {"front": "欲治其国者，先齐其家", "hl": "齐", "word": "齐", "meaning": "使整齐有序", "analogy": "★《大学》"},
  {"front": "致知在格物", "hl": "格物", "word": "格物", "meaning": "推究事物原理", "analogy": "★《大学》"},
  {"front": "今人乍见孺子将入于井", "hl": "乍", "word": "乍", "meaning": "突然", "analogy": "★《孟子》"},
  {"front": "皆有怵惕恻隐之心", "hl": "怵惕恻隐", "word": "怵惕恻隐", "meaning": "惊骇恐惧/哀痛怜悯", "analogy": "★《孟子》"},
  {"front": "非所以要誉于乡党朋友也", "hl": "要", "word": "要(yāo)", "meaning": "博取/求取", "analogy": "★《孟子》"},
  {"front": "有是四端而自谓不能者，自贼者也", "hl": "贼", "word": "贼", "meaning": "伤害", "analogy": "★《孟子》"},
  {"front": "恻隐之心，仁之端也", "hl": "端", "word": "端", "meaning": "萌芽/发端", "analogy": "★《孟子》"},
  {"front": "若火之始然，泉之始达", "hl": "达", "word": "达", "meaning": "流通/涌出", "analogy": "★《孟子》"},
  {"front": "三十辐共一毂", "hl": "毂", "word": "毂(gǔ)", "meaning": "车轮中心", "analogy": "★《老子》"},
  {"front": "埏埴以为器", "hl": "埏埴", "word": "埏埴(shānzhí)", "meaning": "和泥制作陶器", "analogy": "★《老子》"},
  {"front": "企者不立，跨者不行", "hl": "企/跨", "word": "企跨", "meaning": "踮起脚/迈大步", "analogy": "★《老子》"},
  {"front": "自伐者无功，自矜者不长", "hl": "伐/矜", "word": "伐矜", "meaning": "夸耀", "analogy": "★《老子》"},
  {"front": "知足者富，强行者有志", "hl": "强行", "word": "强行", "meaning": "勤勉而行", "analogy": "★《老子》"},
  {"front": "其脆易泮", "hl": "泮", "word": "泮(pàn)", "meaning": "同「判」,分离", "analogy": "★《老子》"},
  {"front": "常于几成而败之", "hl": "几", "word": "几(jī)", "meaning": "接近", "analogy": "★《老子》"},
  {"front": "我树之成而实五石", "hl": "树", "word": "树", "meaning": "种植", "analogy": "★《庄子》"},
  {"front": "剖之以为瓢，则瓠落无所容", "hl": "瓠落", "word": "瓠落(huòluò)", "meaning": "宽大空廓", "analogy": "★《庄子》"},
  {"front": "吾为其无用而掊之", "hl": "掊", "word": "掊(pǒu)", "meaning": "击破", "analogy": "★《庄子》"},
  {"front": "宋人有善为不龟手之药者", "hl": "龟", "word": "龟(jūn)", "meaning": "同「皲」,皮肤冻裂", "analogy": "★《庄子》"},
  {"front": "世世以洴澼纩为事", "hl": "洴澼纩", "word": "洴澼纩(píngpìkuàng)", "meaning": "漂洗丝絮", "analogy": "★《庄子》"},
  {"front": "客得之，以说吴王", "hl": "说", "word": "说(shuì)", "meaning": "劝说/取悦", "analogy": "★《庄子》"},
  {"front": "何不虑以为大樽而浮乎江湖", "hl": "虑", "word": "虑", "meaning": "结缀/考虑", "analogy": "★《庄子》"},
  {"front": "譬之如医之攻人之疾者然", "hl": "攻", "word": "攻", "meaning": "治疗", "analogy": "★《墨子》"},
  {"front": "必知乱之所自起，焉能治之", "hl": "焉", "word": "焉", "meaning": "于是", "analogy": "★《墨子》"},
  {"front": "当察乱何自起", "hl": "当", "word": "当(cháng)", "meaning": "尝试", "analogy": "★《墨子》"},
  {"front": "故亏父而自利", "hl": "亏", "word": "亏", "meaning": "使受损失", "analogy": "★《墨子》"},
  {"front": "视父兄与君若其身，恶施不孝", "hl": "恶施", "word": "恶施(wūshī)", "meaning": "怎么实行", "analogy": "★《墨子》"},
  {"front": "恶得不禁恶而劝爱", "hl": "劝", "word": "劝", "meaning": "鼓励", "analogy": "★《墨子》"},
  {"front": "岂曰无衣？与子同袍", "hl": "同袍", "word": "同袍", "meaning": "长袍/战友", "analogy": "★《无衣》"},
  {"front": "修我戈矛，与子同仇", "hl": "同仇", "word": "同仇", "meaning": "共同对敌", "analogy": "★《无衣》"},
  {"front": "与子偕作", "hl": "偕作", "word": "偕作", "meaning": "一同行动", "analogy": "★《无衣》"},
  {"front": "滟滟随波千万里", "hl": "滟滟", "word": "滟滟(yànyàn)", "meaning": "波光荡漾", "analogy": "★《春江花月夜》"},
  {"front": "江流宛转绕芳甸", "hl": "芳甸", "word": "芳甸(fāngdiàn)", "meaning": "花草茂盛的原野", "analogy": "★《春江花月夜》"},
  {"front": "会须一饮三百杯", "hl": "会须", "word": "会须", "meaning": "应当", "analogy": "★《将进酒》"},
  {"front": "钟鼓馔玉不足贵", "hl": "馔玉", "word": "馔玉(zhuànyù)", "meaning": "珍美的食品", "analogy": "★《将进酒》"},
  {"front": "斗酒十千恣欢谑", "hl": "恣", "word": "恣(zì)", "meaning": "尽情", "analogy": "★《将进酒》"},
  {"front": "径须沽取对君酌", "hl": "径须", "word": "径须", "meaning": "应当", "analogy": "★《将进酒》"},
  {"front": "十年生死两茫茫", "hl": "茫茫", "word": "茫茫", "meaning": "茫然不相知", "analogy": "★《江城子》"},
  {"front": "夜来幽梦忽还乡", "hl": "幽梦", "word": "幽梦", "meaning": "隐约迷离的梦", "analogy": "★《江城子》"},
  {"front": "以吾一日长乎尔，毋吾以也", "hl": "以", "word": "以", "meaning": "因为/同「已」,停止", "analogy": "★《侍坐》"},
  {"front": "居则曰：不吾知也", "hl": "居", "word": "居", "meaning": "平日", "analogy": "★《侍坐》"},
  {"front": "且知方也 / 方六七十", "hl": "方", "word": "方", "meaning": "准则/计量土地", "analogy": "★《侍坐》"},
  {"front": "如五六十 / 如其礼乐", "hl": "如", "word": "如", "meaning": "或者/至于", "analogy": "★《侍坐》"},
  {"front": "以俟君子", "hl": "俟", "word": "俟(sì)", "meaning": "等待", "analogy": "★《侍坐》"},
  {"front": "异乎三子者之撰", "hl": "撰", "word": "撰(zhuàn)", "meaning": "才能", "analogy": "★《侍坐》"},
  {"front": "舍瑟而作", "hl": "作", "word": "作", "meaning": "站起来", "analogy": "★《侍坐》"},
  {"front": "吾与点也", "hl": "与", "word": "与(yǔ)", "meaning": "赞成", "analogy": "★《侍坐》"},
  {"front": "仲尼之徒无道桓文之事者", "hl": "道", "word": "道", "meaning": "讲述", "analogy": "★《齐桓晋文》"},
  {"front": "保民而王，莫之能御也", "hl": "保", "word": "保", "meaning": "安民", "analogy": "★《齐桓晋文》"},
  {"front": "牛何之", "hl": "之", "word": "之", "meaning": "往", "analogy": "★《齐桓晋文》"},
  {"front": "将以衅钟", "hl": "衅", "word": "衅(xìn)", "meaning": "血祭", "analogy": "★《齐桓晋文》"},
  {"front": "舍之！吾不忍其觳觫", "hl": "舍", "word": "舍", "meaning": "释放", "analogy": "★《齐桓晋文》"},
  {"front": "若无罪而就死地", "hl": "就", "word": "就", "meaning": "走向", "analogy": "★《齐桓晋文》"},
  {"front": "百姓皆以王为爱也", "hl": "爱", "word": "爱", "meaning": "吝惜", "analogy": "★《齐桓晋文》"},
  {"front": "王无异于百姓之以王为爱也", "hl": "异", "word": "异", "meaning": "奇怪", "analogy": "★《齐桓晋文》"},
  {"front": "彼恶知之", "hl": "恶", "word": "恶(wū)", "meaning": "怎么", "analogy": "★《齐桓晋文》"},
  {"front": "他人有心，予忖度之", "hl": "度", "word": "度(duó)", "meaning": "揣测/称量", "analogy": "★《齐桓晋文》"},
  {"front": "百姓之不见保", "hl": "见", "word": "见", "meaning": "被", "analogy": "★《齐桓晋文》"},
  {"front": "刑于寡妻", "hl": "刑", "word": "刑", "meaning": "做榜样", "analogy": "★《齐桓晋文》"},
  {"front": "欲辟土地 / 放辟邪侈", "hl": "辟", "word": "辟(pì)", "meaning": "开辟/不正", "analogy": "★《齐桓晋文》"},
  {"front": "殆有甚焉", "hl": "殆", "word": "殆(dài)", "meaning": "恐怕", "analogy": "★《齐桓晋文》"},
  {"front": "盖亦反其本矣", "hl": "盖", "word": "盖(hé)", "meaning": "何不", "analogy": "★《齐桓晋文》"},
  {"front": "是罔民也", "hl": "罔", "word": "罔(wǎng)", "meaning": "陷害", "analogy": "★《齐桓晋文》"},
  {"front": "俯足以畜妻子", "hl": "畜", "word": "畜(xù)", "meaning": "养活", "analogy": "★《齐桓晋文》"},
  {"front": "此惟救死而恐不赡", "hl": "赡", "word": "赡(shàn)", "meaning": "足", "analogy": "★《齐桓晋文》"},
  {"front": "莫不中音", "hl": "中", "word": "中(zhòng)", "meaning": "合乎", "analogy": "★《庖丁解牛》"},
  {"front": "乃中《经首》之会", "hl": "会", "word": "会", "meaning": "节奏", "analogy": "★《庖丁解牛》"},
  {"front": "进乎技矣", "hl": "进", "word": "进", "meaning": "超过", "analogy": "★《庖丁解牛》"},
  {"front": "臣以神遇而不以目视", "hl": "遇", "word": "遇", "meaning": "接触", "analogy": "★《庖丁解牛》"},
  {"front": "批大郤", "hl": "批", "word": "批", "meaning": "击入", "analogy": "★《庖丁解牛》"},
  {"front": "导大窾", "hl": "导", "word": "导", "meaning": "引导/引刀进入", "analogy": "★《庖丁解牛》"},
  {"front": "族庖月更刀 / 每至于族", "hl": "族", "word": "族", "meaning": "众/聚结处", "analogy": "★《庖丁解牛》"},
  {"front": "彼节者有间", "hl": "间", "word": "间(jiàn)", "meaning": "空隙", "analogy": "★《庖丁解牛》"},
  {"front": "如土委地", "hl": "委", "word": "委", "meaning": "散落", "analogy": "★《庖丁解牛》"},
  {"front": "善刀而藏之", "hl": "善", "word": "善", "meaning": "揩拭", "analogy": "★《庖丁解牛》"},
  {"front": "晋军函陵", "hl": "军", "word": "军", "meaning": "驻扎", "analogy": "★《烛之武》"},
  {"front": "且贰于楚也", "hl": "贰", "word": "贰", "meaning": "亲附", "analogy": "★《烛之武》"},
  {"front": "辞曰：臣之壮也，犹不如人", "hl": "辞", "word": "辞", "meaning": "推辞", "analogy": "★《烛之武》"},
  {"front": "越国以鄙远", "hl": "鄙", "word": "鄙", "meaning": "边邑", "analogy": "★《烛之武》"},
  {"front": "焉用亡郑以陪邻", "hl": "陪", "word": "陪", "meaning": "增加", "analogy": "★《烛之武》"},
  {"front": "共其乏困", "hl": "共", "word": "共(gōng)", "meaning": "供给", "analogy": "★《烛之武》"},
  {"front": "且君尝为晋君赐矣", "hl": "赐", "word": "赐", "meaning": "恩惠", "analogy": "★《烛之武》"},
  {"front": "朝济而夕设版焉", "hl": "济", "word": "济", "meaning": "渡河", "analogy": "★《烛之武》"},
  {"front": "既东封郑", "hl": "封", "word": "封", "meaning": "疆界", "analogy": "★《烛之武》"},
  {"front": "又欲肆其西封", "hl": "肆", "word": "肆", "meaning": "扩张", "analogy": "★《烛之武》"},
  {"front": "若不阙秦", "hl": "阙", "word": "阙(jué)", "meaning": "侵损", "analogy": "★《烛之武》"},
  {"front": "微夫人之力不及此", "hl": "微", "word": "微", "meaning": "没有", "analogy": "★《烛之武》"},
  {"front": "失其所与，不知", "hl": "与", "word": "与", "meaning": "同盟者", "analogy": "★《烛之武》"},
  {"front": "沛公欲王关中", "hl": "王", "word": "王(wàng)", "meaning": "称王", "analogy": "★《鸿门宴》"},
  {"front": "妇女无所幸", "hl": "幸", "word": "幸", "meaning": "宠爱", "analogy": "★《鸿门宴》"},
  {"front": "素善留侯张良", "hl": "善", "word": "善", "meaning": "交好", "analogy": "★《鸿门宴》"},
  {"front": "距关，毋内诸侯", "hl": "距/内", "word": "距内", "meaning": "据守/接纳", "analogy": "★《鸿门宴》"},
  {"front": "料大王士卒足以当项王乎", "hl": "当", "word": "当(dāng)", "meaning": "对等", "analogy": "★《鸿门宴》"},
  {"front": "项伯杀人，臣活之", "hl": "活", "word": "活", "meaning": "使……活命", "analogy": "★《鸿门宴》"},
  {"front": "张良出，要项伯", "hl": "要", "word": "要(yāo)", "meaning": "邀请", "analogy": "★《鸿门宴》"},
  {"front": "籍吏民，封府库", "hl": "籍", "word": "籍", "meaning": "造册登记", "analogy": "★《鸿门宴》"},
  {"front": "备他盗之出入与非常也", "hl": "非常", "word": "非常(古)", "meaning": "意外变故", "analogy": "★《鸿门宴》"},
  {"front": "愿伯具言臣之不敢倍德也", "hl": "倍", "word": "倍", "meaning": "背弃", "analogy": "★《鸿门宴》"},
  {"front": "旦日不可不蚤自来谢项王", "hl": "谢", "word": "谢", "meaning": "道歉/辞别", "analogy": "★《鸿门宴》"},
  {"front": "然不自意能先入关破秦", "hl": "意", "word": "意", "meaning": "料想", "analogy": "★《鸿门宴》"},
  {"front": "范增数目项王", "hl": "目", "word": "目", "meaning": "递眼色", "analogy": "★《鸿门宴》"},
  {"front": "常以身翼蔽沛公", "hl": "翼蔽", "word": "翼蔽(yìbì)", "meaning": "遮护", "analogy": "★《鸿门宴》"},
  {"front": "哙遂入，披帷西向立", "hl": "披", "word": "披", "meaning": "分开", "analogy": "★《鸿门宴》"},
  {"front": "项王按剑而跽", "hl": "跽", "word": "跽(jì)", "meaning": "挺直身子", "analogy": "★《鸿门宴》"},
  {"front": "刑人如恐不胜 / 不胜杯杓", "hl": "胜", "word": "胜", "meaning": "尽/承受", "analogy": "★《鸿门宴》"},
  {"front": "大礼不辞小让", "hl": "让", "word": "让", "meaning": "责备", "analogy": "★《鸿门宴》"},
  {"front": "大王来何操", "hl": "操", "word": "操", "meaning": "拿", "analogy": "★《鸿门宴》"},
  {"front": "道芷阳间行", "hl": "道/间", "word": "道间", "meaning": "取道/秘密地", "analogy": "★《鸿门宴》"},
  {"front": "闻大王有意督过之", "hl": "督过", "word": "督过", "meaning": "责备", "analogy": "★《鸿门宴》"},
  {"front": "并国二十", "hl": "并", "word": "并", "meaning": "兼并", "analogy": "★《谏逐客书》"},
  {"front": "举地千里", "hl": "举", "word": "举", "meaning": "攻克", "analogy": "★《谏逐客书》"},
  {"front": "拔三川之地", "hl": "拔", "word": "拔", "meaning": "攻取", "analogy": "★《谏逐客书》"},
  {"front": "向使四君却客而不内", "hl": "内", "word": "内(nà)", "meaning": "接纳", "analogy": "★《谏逐客书》"},
  {"front": "服太阿之剑", "hl": "服", "word": "服", "meaning": "佩带", "analogy": "★《谏逐客书》"},
  {"front": "而陛下说之", "hl": "说", "word": "说(yuè)", "meaning": "喜欢", "analogy": "★《谏逐客书》"},
  {"front": "今乃弃黔首以资敌国", "hl": "资", "word": "资", "meaning": "资助", "analogy": "★《谏逐客书》"},
  {"front": "却宾客以业诸侯", "hl": "业", "word": "业", "meaning": "使成就霸业", "analogy": "★《谏逐客书》"},
  {"front": "藉寇兵而赍盗粮", "hl": "赍", "word": "赍(jī)", "meaning": "送给", "analogy": "★《谏逐客书》"},
  {"front": "臣闻求木之长者，必固其根本", "hl": "长", "word": "长(zhǎng)", "meaning": "生长", "analogy": "★《谏太宗十思疏》"},
  {"front": "必浚其泉源", "hl": "浚", "word": "浚(jùn)", "meaning": "疏通", "analogy": "★《谏太宗十思疏》"},
  {"front": "人君当神器之重", "hl": "当", "word": "当", "meaning": "掌握", "analogy": "★《谏太宗十思疏》"},
  {"front": "永保无疆之休", "hl": "休", "word": "休", "meaning": "喜庆", "analogy": "★《谏太宗十思疏》"},
  {"front": "能克终者盖寡", "hl": "克", "word": "克", "meaning": "能够", "analogy": "★《谏太宗十思疏》"},
  {"front": "既得志，则纵情以傲物", "hl": "物", "word": "物", "meaning": "人", "analogy": "★《谏太宗十思疏》"},
  {"front": "虽董之以严刑", "hl": "董", "word": "董(dǒng)", "meaning": "督察", "analogy": "★《谏太宗十思疏》"},
  {"front": "振之以威怒", "hl": "振", "word": "振", "meaning": "威吓", "analogy": "★《谏太宗十思疏》"},
  {"front": "简能而任之", "hl": "简", "word": "简", "meaning": "选拔", "analogy": "★《谏太宗十思疏》"},
  {"front": "所操之术多异故也", "hl": "操", "word": "操", "meaning": "持", "analogy": "★《答司马谏议书》"},
  {"front": "终必不蒙见察", "hl": "察", "word": "察", "meaning": "理解", "analogy": "★《答司马谏议书》"},
  {"front": "故略上报", "hl": "报", "word": "报", "meaning": "回信", "analogy": "★《答司马谏议书》"},
  {"front": "不复一一自辩", "hl": "辩", "word": "辩", "meaning": "分辩", "analogy": "★《答司马谏议书》"},
  {"front": "故今具道所以", "hl": "具", "word": "具", "meaning": "详细", "analogy": "★《答司马谏议书》"},
  {"front": "难壬人", "hl": "难", "word": "难(nàn)", "meaning": "排斥", "analogy": "★《答司马谏议书》"},
  {"front": "盘庚不为怨者故改其度", "hl": "度", "word": "度(dù)", "meaning": "计划", "analogy": "★《答司马谏议书》"},
  {"front": "度义而后动", "hl": "度", "word": "度(duó)", "meaning": "考虑", "analogy": "★《答司马谏议书》"},
  {"front": "以膏泽斯民", "hl": "膏泽", "word": "膏泽(gāozé)", "meaning": "施恩惠", "analogy": "★《答司马谏议书》"},
  {"front": "六王毕，四海一", "hl": "一", "word": "一", "meaning": "统一", "analogy": "★《阿房宫赋》"},
  {"front": "蜀山兀，阿房出", "hl": "兀", "word": "兀(wù)", "meaning": "光秃", "analogy": "★《阿房宫赋》"},
  {"front": "直走咸阳", "hl": "走", "word": "走", "meaning": "通达", "analogy": "★《阿房宫赋》"},
  {"front": "矗不知其几千万落", "hl": "矗", "word": "矗(chù)", "meaning": "矗立", "analogy": "★《阿房宫赋》"},
  {"front": "而望幸焉", "hl": "幸", "word": "幸", "meaning": "帝王到某处", "analogy": "★《阿房宫赋》"},
  {"front": "剽掠其人", "hl": "剽", "word": "剽(piāo)", "meaning": "抢劫", "analogy": "★《阿房宫赋》"},
  {"front": "函谷举", "hl": "举", "word": "举", "meaning": "攻占", "analogy": "★《阿房宫赋》"},
  {"front": "族秦者秦也", "hl": "族", "word": "族", "meaning": "灭族", "analogy": "★《阿房宫赋》"},
  {"front": "则递三世可至万世而为君", "hl": "递", "word": "递", "meaning": "依次", "analogy": "★《阿房宫赋》"},
  {"front": "弊在赂秦", "hl": "弊", "word": "弊", "meaning": "弊端", "analogy": "★《六国论》"},
  {"front": "不能独完", "hl": "完", "word": "完", "meaning": "保全", "analogy": "★《六国论》"},
  {"front": "故不战而强弱胜负已判矣", "hl": "判", "word": "判", "meaning": "确定", "analogy": "★《六国论》"},
  {"front": "与嬴而不助五国也", "hl": "与", "word": "与", "meaning": "亲附", "analogy": "★《六国论》"},
  {"front": "始速祸焉", "hl": "速", "word": "速", "meaning": "招致", "analogy": "★《六国论》"},
  {"front": "李牧连却之", "hl": "却", "word": "却", "meaning": "打退", "analogy": "★《六国论》"},
  {"front": "洎牧以谗诛", "hl": "洎", "word": "洎(jì)", "meaning": "等到", "analogy": "★《六国论》"},
  {"front": "为秦人积威之所劫", "hl": "劫", "word": "劫", "meaning": "胁迫", "analogy": "★《六国论》"},
  {"front": "下而从六国破亡之故事", "hl": "故事", "word": "故事(古)", "meaning": "旧事", "analogy": "★《六国论》"},
];
